twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        notificationService: '@App\Services\NotificationService'
when@test:
    twig:
        strict_variables: true
